
export const types = {
    ADD_BET: `ADD_BET`,
    SET_FLASH_MSG: `SET_FLASH_MSG`,
    SET_SELECTED_DRAW_TIME: `SET_SELECTED_DRAW_TIME`,
    SET_SELECTED_DATE: `SET_SELECTED_DATE`,
    SET_WINNING_INFO: `SET_WINNING_INFO`,
    SET_BET_LIST: `SET_BET_LIST`,
    DELETE_BET_NUMBER: `DELETE_BET_NUMBER`,
    SET_IS_LOADING:`SET_IS_LOADING`,
    
}